import enum


class PaperStatus(str, enum.Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"


class SectionType(str, enum.Enum):
    ABSTRACT = "ABSTRACT"
    INTRODUCTION = "INTRODUCTION"
    RELATED_WORK = "RELATED_WORK"
    METHODOLOGY = "METHODOLOGY"
    DATASET = "DATASET"
    EXPERIMENTS = "EXPERIMENTS"
    RESULTS = "RESULTS"
    DISCUSSION = "DISCUSSION"
    LIMITATIONS = "LIMITATIONS"
    CONCLUSION = "CONCLUSION"
    REFERENCES = "REFERENCES"
    OTHER = "OTHER"


class QuestionType(str, enum.Enum):
    PROBLEM = "PROBLEM"
    OBJECTIVE = "OBJECTIVE"
    CONTRIBUTION = "CONTRIBUTION"
    METHODOLOGY = "METHODOLOGY"
    MODEL = "MODEL"
    ALGORITHM = "ALGORITHM"
    DATASET = "DATASET"
    EXPERIMENT = "EXPERIMENT"
    RESULT = "RESULT"
    METRIC = "METRIC"
    LIMITATION = "LIMITATION"
    FUTURE_WORK = "FUTURE_WORK"
    GENERAL = "GENERAL"
    UNKNOWN = "UNKNOWN"


class RetrievalMode(str, enum.Enum):
    BASELINE_RAG = "BASELINE_RAG"
    STRUCTURE_AWARE_RAG = "STRUCTURE_AWARE_RAG"


class ContributionType(str, enum.Enum):
    EXPLICIT = "EXPLICIT"
    INFERRED = "INFERRED"


class PipelineStage(str, enum.Enum):
    UPLOADING = "UPLOADING"
    EXTRACTING = "EXTRACTING"
    STRUCTURING = "STRUCTURING"
    CHUNKING = "CHUNKING"
    EMBEDDING = "EMBEDDING"
    ANALYZING = "ANALYZING"
    READY = "READY"
    FAILED = "FAILED"
